/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.battleships;

import net.battleships.content.ContentLoader;

import java.nio.file.AccessDeniedException;

public class Main {
	public String test = "test";

	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		try {
			ContentLoader contentLoader = new ContentLoader(ContentLoader.getOSType());
		} catch (AccessDeniedException e) {
			e.printStackTrace();
		}
		Main thisObject = new Main();
		System.out.println(thisObject.getGreeting());
	}
}