/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.battleships;

import com.google.gson.*;

public class Main {
	public String test = "test";

	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		Main thisObject = new Main();
		System.out.println(thisObject.getGreeting());
		GsonBuilder gsonBuilder = new GsonBuilder();
		Gson gson = gsonBuilder.create();
		System.out.println(gson.toJson(thisObject));
		System.out.println(gson.fromJson(gson.toJson(thisObject), Main.class));
		System.out.println(gson.toJson(gson.fromJson(gson.toJson(thisObject), Main.class)));
	}
}