/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.battleships;

import java.util.ArrayList;

public class Main {
	public String test = "test";

	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		Main thisObject = new Main();
		System.out.println(thisObject.getGreeting());
		ArrayList<String> gfg = new ArrayList<String>() {
			{
				add("Geeks");
				add("for");
				add("Geeks");
			}
		};

		// print ArrayList
		System.out.println("ArrayList : " + gfg);
	}
}