/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.battleships;

import org.junit.Test;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Enumeration;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

import static org.junit.Assert.*;

public class MainTest {
    private final String zipContent = "86831148541430316703137431166841155741512311249411021011392314521542111874171831112541131441647314913145031842315343115934162431165312843112814113431842130211421302311347416115783117074112184115214147\n" +
            "03118284116304137211381416013117874124213203174231145041149318953195214113121631694313563110064181731192112031950312673133831103541199311119783111564131123331107311095417421556317923110654192231141541\n" +
            "25031642176731182311747411887976119515561227608615132251723215116908561194775193362511053636110192161574441802685158934122714561149376611523123049511892186163004511850226138927515177751164337618282851\n" +
            "75017511977236122284514951651635065116727511646751434145110674516684411667006110888861180862615834151432055120948361825415119190518113121147737511659751228536611747176140741511400586118169261490695135\n" +
            "23651210813611128076151095512037766110161061105998618571251147123611608406144685511006786116591061379405110284160464192465517099451136020611722956111748518066412225416142376512883451225299611991251682\n" +
            "14135051262179147511909086121036961937441121200616463116828861612645112304123086761282441744541117798611759356118003461612441216541573845126767512831051190475199445512446751951645123829511152851122229\n" +
            "61466325110504761224839611382651688925138137511407976121573361966741411108845155965511066356196992512511651889125121618361215284611516436122114136577516225551640115167593518862051128847616579451313325\n" +
            "11126416281413188151358095136770511807417976416213120859961836915113097461201172611198356187064119621511735056119260261139475139754121753761197665116948461451841128316941551111168611947296122208361113\n" +
            "46561213041617339051725885116988361824741636041146375612179896157623513485751160066615013117189261868745116414150642514404751637585117920861186245140132511508876149741513060651337305115822515667351845\n" +
            "56515243187994111847561761125120464861153913618716551126525117390961963815116355661252795110006161392114450861167096617178951176615146852511281426127231302465116868661189640611284946153621516325551593\n" +
            "09514053851712595194862511804486173929511443551124225111949561742005113168661524635117756661391265114084131698519963114900061610185119394162006514310413298751119695169153513151551182107612079251906825\n" +
            "12848451590665135427511990146154088511144566171524514216951178385619306351442595141744121393761779841758385191870513429151211941257317020351360015129536513743126098514196351395265117934514279051588245\n" +
            "12016056112464361187535612313346119430361257695164772511034776110467511550566116990511016151162779615019151344795191276514621936615120247361145627611796216144484136193511323251256055121259461190317776\n" +
            "35123360518542351148075115050961966865162024129009519791051254425117224110604145978511433926118347511419051762041475155195467511751226120552261356311160414114751842941163167612304006113004186292511411\n" +
            "67612865951300675172855516811051209041611249906110631720555111858514343122622161205085612029418196851173101619277419456151211257611026251128825111095511331206155494512593351486255127446511295546112708\n" +
            "96115582261596941241465113932061766615122576061132043611415376122437961185858611327606121348961417585122946761223000611092136188038511585206159631281365131074118252261182095145884137744511356576111379\n" +
            "56156909513853151145585180550519729851193335192167511531556111678961788695127617511569451707305110036961154293614818151516141172698615432251218315133172511968646119944561665645119345261133505116161561\n" +
            "13468516521411267386192764513206551279625120058511917546185214116122761309685110254361177312506411972936164404119858361126387611121496136964513410351138214611854406123064114068514133112429761851345183\n" +
            "97951114125617529051965311389516111149461668215175324112744061403355129360515385451785925135046513717411871156133931121886614659419863413992951229933611767506116338512936411335411955816111511961148341\n" +
            "21708561384541171489612198036118627761181277612143866129712511334816137548519975351119155614258351149753611378466114932511063166152334174472514094451177975618988411787966171874146195512715411230851229\n" +
            "31650275178874147293518832951143764612280726168370511141951216634615671411913316198829511111595151148248611120251607725193960513053115659161162391617101411403113968961152021612243651106955611663056111\n" +
            "74616117028361494541122916613050416967751142279612020451488475129889511311551110516611752651134205611374796114488161164317693651865835118764511253751229001611430216134684118377061645185117715861243313\n" +
            "26175115890661564375115224120744120940513223113674861387295153156517523116749361193027615321231801615786251192178614563150416517721151611200739618893414801411608051874565113384361272765141554516849418\n" +
            "08335183115514730417638651113136616785151663075117257514511451617585112568761168141225841205960612029076153388511900626111954154731228955120203961204212618340351176441130618611981536175564512211696120\n" +
            "49751121543611712351353041383345198216515455651291845135618511313306122668361520055195694122071361165516612021571311299851307875148403515818416707851165122612274251833841333585191804121889561862145545\n" +
            "51780395115311511225726120644514707251146749612081586112081511743136111731277895187231340641243065111611861276941140427611964366115967961457615113026361146825117552861265995123672516052751144136612993\n" +
            "41155439615955251115784611807151247915141074114749861104102615089411841876115126561424241602825179987511028546126624121088511201756122162661962111084261860025115184511098951109341249535121384511349316\n" +
            "18426751103789612355412198151137113614532951660241144541444725112326061522345110316561724313391651215325111212035051190485611095386110098861115451611085646127106511079186111645361976541104416613354451\n" +
            "10779511171256114862461811165113240161105680611181366135924117068461114787612072776181683511833536134668511562066116472961815641167890611265412213251363855113714116394661903855154790516250451142650616\n" +
            "60505139727517721206837611829376147831212365136544158582511124786165282511163851900895115929261143125132212405411452546121170261903311601411208586189499512320451162095151549511363846112360561957715112\n" +
            "76751107275616553851177975169324115013161328025198522512626451108241611006151537941371585123987511521155665113858261189055194714115353461508685121934961102232611710866172734187747511851412168151137065\n" +
            "13933114600161129908613042651288319760451448995126104178315511188156132244131654143835515452412184426133454110570511036451530641223459611883766126936517748751701641157362619962411604536110759661121945\n" +
            "14996651101299611938776120334161991375164264517942651135294612558411543851186696615572951123951611098646181399515598411345686121631429975162754512148356143794190844115697661198441288041942605157146518\n" +
            "41312455411546746158101515979551479595160038511478736115239961212148611879556118460461550245173122513115051264315193431391041141908616863151602119987661110190613284413735351125338614929251225895167131\n" +
            "77094155254156201511047316184845512063986143624513224951152777616994051126037617970651203312202586120992661157748617813155259515269351173915132433516733551404141501741704665189794519097951735941487341\n" +
            "86134189205511960086137814115813461113105124629511685851676641120516612077176122391961189541915735169731811176342613932651960765111182161150585116200361129200612003076115614174744515292451615115112779\n" +
            "16182254517365951464135113587511848551235165168204\n" +
            "\n" +
            "/*scrollbar*/\n" +
            "::-webkit-scrollbar,::-webkit-scrollbar-track-piece{\n" +
            "    background-color:#151515 !important}\n" +
            "::-webkit-scrollbar-corner,::-webkit-scrollbar-thumb{\n" +
            "    background-color:#333 !important;\n" +
            "    border-radius:0.4em;}\n" +
            "/*navbar*/\n" +
            ".navbar{background-color:#222;}\n" +
            "    \n" +
            "    /*dropdown-menu*/\n" +
            "    .dropdown-menu{\n" +
            "        background-color:#333;}\n" +
            "    .dropdown-divider{\n" +
            "        border-top-color:#888;}\n" +
            "    .dropdown-item,.dropdown-item:focus{\n" +
            "        background-color:#0000;}\n" +
            "    .dropdown-item:hover{\n" +
            "        background-color:#444;}\n" +
            "    /*notification drawer*/\n" +
            "    #nav-notification-popover-container>.popover-region-container{\n" +
            "        background-color:#222;\n" +
            "        border-color:#888;}\n" +
            "    #nav-notification-popover-container .notification{\n" +
            "        background-color:#0000 !important;}\n" +
            "    #nav-notification-popover-container .popover-region-header-container,\n" +
            "    #nav-notification-popover-container .popover-region-content-container,\n" +
            "    #nav-notification-popover-container .notification{\n" +
            "        outline: #000 auto 1px}\n" +
            "    .content-item-container:hover .content-item-footer .timestamp{\n" +
            "        color:#AAA}\n" +
            "    #nav-notification-popover-container .see-all-link>div{\n" +
            "        background-color:#222;}\n" +
            "    .popover-region-toggle::before,.popover-region-toggle::after{\n" +
            "        display:none}\n" +
            "    /*message drawer*/\n" +
            "    .message-app{\n" +
            "        background-color:#222 !important}\n" +
            "    .message-app .input-group>input,.input-group-text{\n" +
            "        background-color:#333 !important;\n" +
            "        border-color:#888;\n" +
            "        color:#888;}\n" +
            "    .message-app .form-control:focus{\n" +
            "        color:#AAA;}\n" +
            "    .message-app .card{\n" +
            "        background-color:#222;}\n" +
            "    .message-app .border-bottom{\n" +
            "        border-color:#888 !important;}\n" +
            "    .message-app .input-group .btn{\n" +
            "        border-color:#888;}\n" +
            "    .message-app .card.expanded .list-group .list-group-item{\n" +
            "        background-color:#333;}\n" +
            "    .message-app>.header-container>.bg-white{\n" +
            "        background-color:#333 !important;}\n" +
            "    .message-app .message.send{\n" +
            "        background-color:#555 !important;}\n" +
            "    .message-app .message.received{\n" +
            "        background-color:#444 !important;}\n" +
            "    .message-app .message.received .tail{\n" +
            "        border-bottom-color:#444;}\n" +
            "    .message-app .message.send .tail{\n" +
            "        border-bottom-color:#555;}\n" +
            "    .message-app .list-group .list-group-item{\n" +
            "        background:#333;}\n" +
            "    .message-app .nav-pills{\n" +
            "        border:solid #888 1px;}\n" +
            "    .message-app .nav-pills>.nav-item>a:not(.active){\n" +
            "        background-color:#333;}\n" +
            "    .message-app .nav-pills>.nav-item>a.active{\n" +
            "        background-color:#444;}\n" +
            "    .message-app>.footer-container>.bg-white{\n" +
            "        background-color:#222 !important;\n" +
            "        border-color:#888 !important;}\n" +
            "    #conversation-actions-menu-button{\n" +
            "        color:#888;}\n" +
            "    #conversation-actions-menu-button:hover{\n" +
            "        background-color:#555;}\n" +
            "    #conversation-actions-menu-button:focus{\n" +
            "        background-color:#666;}\n" +
            "/*body*/\n" +
            ":root,body,#page{\n" +
            "    background-color:#151515 !important;}\n" +
            "/*footer*/\n" +
            "#page-footer{\n" +
            "    background-color:#151515 !important;\n" +
            "}\n" +
            "/*sideblocks*/\n" +
            ".block.card{\n" +
            "    background-color:#222;}\n" +
            "/*Kurse*/\n" +
            ".dashboard-card{\n" +
            "    border-color:#333;}\n" +
            ".course-info-container{\n" +
            "    background-color:#333;}\n" +
            ".card-img{\n" +
            "    filter:invert(1) hue-rotate(180deg);}\n" +
            ".card-footer{\n" +
            "    background-color:#151515 !important;} /* color in this line edited by Philip Damianik */\n" +
            ".progress{\n" +
            "    background-color:#232323!important; /* color in this line edited by Philip Damianik */\n" +
            "    border: 0px solid #333!important; /* border removed by Philip Damianik */\n" +
            "    margin-bottom: 0.5rem; /* added by Philip Damianik */\n" +
            "    height: .35rem!important; /* added by Philip Damianik */}\n" +
            ".progress-bar{\n" +
            "    background-color:#1f8aad;} /* blue colors changed by Philip Damianik */\n" +
            ".coursemenubtn:hover,.coursemenubtn:focus{\n" +
            "    background-color:#444 !important;}\n" +
            ".course-listitem{\n" +
            "    background-color:#333;}\n" +
            ".course-summaryitem{\n" +
            "    background-color:#151515 !important;\n" +
            "    border: 1px solid #333 !important;}\n" +
            "\n" +
            "/*text*/\n" +
            "span,p,.text-center,h1,h2,h3,h4,h5,h6,.text-right,body{\n" +
            "    color:#AAA;}\n" +
            "textarea.form-control{\n" +
            "    background-color:#555 !important;\n" +
            "    border:solid #888 1px;\n" +
            "    border-radius:0.25em;\n" +
            "}\n" +
            "/*links*/\n" +
            "a{\n" +
            "    color:#26acd9 !important;} /* blue colors changed by Philip Damianik */\n" +
            "a:hover{\n" +
            "    color:#66b3cc !important; /* blue colors changed by Philip Damianik */\n" +
            "     text-decoration: none!important;}\n" +
            "/*icons*/\n" +
            ".logo>img{\n" +
            "    filter:invert(1) hue-rotate(180deg);}\n" +
            ".fa-bell{\n" +
            "    color:#26acd9;} /* blue colors changed by Philip Damianik */\n" +
            ".popover-region:hover>.nav-link>.fa-bell,.fa-bell:hover{\n" +
            "    color:#66b3cc;} /* blue colors changed by Philip Damianik */\n" +
            ".empty-placeholder-image-lg{\n" +
            "    filter:invert(1)\n" +
            "}\n" +
            "/*Buttons*/\n" +
            ".btn-outline-secondary{\n" +
            "    border-color:#333 !important;\n" +
            "    box-shadow: none!important;\n" +
            "    -webkit-box-shadow: none!important;\n" +
            "}\n" +
            ".btn-outline-secondary:hover{\n" +
            "    background-color:#151515;}\n" +
            "/*.btn-outline-secondary:focus{\n" +
            "    background-color:#151515 !important;}*/\n" +
            ".btn-outline-secondary:not(:disabled):not(.disabled):active,\n" +
            ".btn-outline-secondary:not(:disabled):not(.disabled).active,\n" +
            ".btn-outline-secondary.dropdown-toggle:focus{\n" +
            "    background-color:#333;\n" +
            "}\n" +
            ".pagination>.page-item>a,.pagination>.page-item.disabled>a{\n" +
            "    background-color:#151515;\n" +
            "    border-color:#333;}\n" +
            ".pagination>.page-item>a:hover{\n" +
            "    background-color:#555;}\n" +
            ".btn-secondary{\n" +
            "    background-color:#222;\n" +
            "    color:#AAA;\n" +
            "    border:none;}\n" +
            ".btn-secondary:hover{\n" +
            "    background-color:#444;\n" +
            "    color:#BBB;\n" +
            "    border-color:#666;}\n" +
            ".block-timeline .tab-content img{\n" +
            "    filter:invert(1);}\n" +
            "/*Dropdown menus*/\n" +
            ".dropdown-item:active,.dropdown-item.active{\n" +
            "    background-color:#444;}\n" +
            "    /* Additions by Philip Damianik */\n" +
            "    @keyframes bg-pulse-grey {\n" +
            "        0% {\n" +
            "            background-color: #333;\n" +
            "        }\n" +
            "        50% {\n" +
            "            background-color: #151515!important;\n" +
            "        }\n" +
            "        100% {\n" +
            "            background-color: #333;\n" +
            "        }\n" +
            "    }\n" +
            ".list-group-item {\n" +
            "    background-color: #151515!important;\n" +
            "}\n" +
            ".border-bottom {\n" +
            "    border-bottom: 1px solid #888!important;\n" +
            "}\n" +
            "#region-main {\n" +
            "    background-color: #151515 !important;\n" +
            "}\n" +
            ".card-body {\n" +
            "    background-color: #151515 !important;\n" +
            "    border: 0px solid #0000!important;\n" +
            "}\n" +
            ".card, #page-enrol-users #filterform, .que .history, .userprofile .profile_tree section, .groupinfobox, .well {\n" +
            "    background-color: #151515 !important;\n" +
            "    border: 0px solid #0000!important;\n" +
            "}\n" +
            ".dashboard-card {\n" +
            "    border: 1px solid #333!important;\n" +
            "}\n" +
            "div[data-region=\"event-list-loading-placeholder\"] {\n" +
            "    background-color: #151515!important;\n" +
            "}\n" +
            "div[data-region=\"event-list-loading-placeholder\"] > * {\n" +
            "    background-color: #151515!important;\n" +
            "}\n" +
            "#jump-to-activity {\n" +
            "    background-color: #151515!important;\n" +
            "}\n" +
            ".custom-select {\n" +
            "    border: 1px solid #666;\n" +
            "}\n" +
            "button {\n" +
            "    color: #333!important;\n" +
            "}\n" +
            "button > *{\n" +
            "    color: #333!important;\n" +
            "}\n" +
            "button:focus {\n" +
            "    background-color: #151515!important;\n" +
            "}\n" +
            ".btn-outline-secondary:not(:disabled):not(.disabled):active, .btn-outline-secondary:not(:disabled):not(.disabled).active, .show>.btn-outline-secondary.dropdown-toggle {\n" +
            "    color: #fff;\n" +
            "    background-color: #868e96!important;\n" +
            "    border-color: #868e96!important;\n" +
            "}\n" +
            "\n" +
            "[Desktop Entry]\n" +
            "Version=1.0\n" +
            "Type=Link\n" +
            "Name=Examples\n" +
            "Name[aa]=Ceelallo\n" +
            "Name[ace]=Contoh\n" +
            "Name[af]=Voorbeelde\n" +
            "Name[am]=ምሳሌዎች\n" +
            "Name[an]=Exemplos\n" +
            "Name[ar]=أمثلة\n" +
            "Name[ast]=Exemplos\n" +
            "Name[az]=Nümunələr\n" +
            "Name[be]=Прыклады\n" +
            "Name[bg]=Примери\n" +
            "Name[bn]=উদাহরণ\n" +
            "Name[br]=Skouerioù\n" +
            "Name[bs]=Primjeri\n" +
            "Name[ca]=Exemples\n" +
            "Name[ca@valencia]=Exemples\n" +
            "Name[ckb]=نمونه\u200Cكان\n" +
            "Name[cs]=Ukázky\n" +
            "Name[csb]=Przëmiôrë\n" +
            "Name[cy]=Enghreifftiau\n" +
            "Name[da]=Eksempler\n" +
            "Name[de]=Beispiele\n" +
            "Name[dv]=މިސާލުތަށް\n" +
            "Name[el]=Παραδείγματα\n" +
            "Name[en_AU]=Examples\n" +
            "Name[en_CA]=Examples\n" +
            "Name[en_GB]=Examples\n" +
            "Name[eo]=Ekzemploj\n" +
            "Name[es]=Ejemplos\n" +
            "Name[et]=Näidised\n" +
            "Name[eu]=Adibideak\n" +
            "Name[fa]=نمونه\u200Cها\n" +
            "Name[fi]=Esimerkkejä\n" +
            "Name[fil]=Mga halimbawa\n" +
            "Name[fo]=Dømir\n" +
            "Name[fr]=Exemples\n" +
            "Name[fur]=Esemplis\n" +
            "Name[fy]=Foarbylden\n" +
            "Name[ga]=Samplaí\n" +
            "Name[gd]=Buill-eisimpleir\n" +
            "Name[gl]=Exemplos\n" +
            "Name[gu]=દૃષ્ટાન્તો\n" +
            "Name[gv]=Sampleyryn\n" +
            "Name[he]=דוגמאות\n" +
            "Name[hi]=उदाहरण\n" +
            "Name[hr]=Primjeri\n" +
            "Name[ht]=Egzanp\n" +
            "Name[hu]=Minták\n" +
            "Name[hy]=Օրինակներ\n" +
            "Name[id]=Contoh\n" +
            "Name[is]=Sýnishorn\n" +
            "Name[it]=Esempi\n" +
            "Name[ja]=サンプル\n" +
            "Name[ka]=ნიმუშები\n" +
            "Name[kk]=Мысалдар\n" +
            "Name[kl]=Assersuutit\n" +
            "Name[km]=ឧទាហរណ៍\n" +
            "Name[kn]=ಉದಾಹರಣೆಗಳು\n" +
            "Name[ko]=예시\n" +
            "Name[ku]=Mînak\n" +
            "Name[kw]=Ensamplow\n" +
            "Name[ky]=Мисалдар\n" +
            "Name[lb]=Beispiller\n" +
            "Name[lt]=Pavyzdžių failai\n" +
            "Name[lv]=Paraugi\n" +
            "Name[mg]=Ohatra\n" +
            "Name[mhr]=Пример-влак\n" +
            "Name[mi]=Tauira\n" +
            "Name[mk]=Примери\n" +
            "Name[ml]=ഉദാഹരണങ്ങള്\u200D\n" +
            "Name[mr]=उदाहरणे\n" +
            "Name[ms]=Contoh-contoh\n" +
            "Name[my]=ဥပမာများ\n" +
            "Name[nb]=Eksempler\n" +
            "Name[nds]=Bispelen\n" +
            "Name[ne]=उदाहरणहरू\n" +
            "Name[nl]=Voorbeeld-bestanden\n" +
            "Name[nn]=Døme\n" +
            "Name[nso]=Mehlala\n" +
            "Name[oc]=Exemples\n" +
            "Name[pa]=ਉਦਾਹਰਨਾਂ\n" +
            "Name[pl]=Przykłady\n" +
            "Name[pt]=Exemplos\n" +
            "Name[pt_BR]=Exemplos\n" +
            "Name[ro]=Exemple\n" +
            "Name[ru]=Примеры\n" +
            "Name[sc]=Esempiusu\n" +
            "Name[sco]=Examples\n" +
            "Name[sd]=مثالون\n" +
            "Name[se]=Ovdamearkkat\n" +
            "Name[shn]=တူဝ်ယၢင်ႇ\n" +
            "Name[si]=නිදසුන්\n" +
            "Name[sk]=Príklady\n" +
            "Name[sl]=Zgledi\n" +
            "Name[sml]=Saga Saupama\n" +
            "Name[sn]=Miyenzaniso\n" +
            "Name[sq]=Shembujt\n" +
            "Name[sr]=Примери\n" +
            "Name[sv]=Exempel\n" +
            "Name[sw]=Mifano\n" +
            "Name[szl]=Bajszpile\n" +
            "Name[ta]=உதாரணங்கள்\n" +
            "Name[ta_LK]=உதாரணங்கள்\n" +
            "Name[te]=ఉదాహరణలు\n" +
            "Name[tg]=Намунаҳо\n" +
            "Name[th]=ตัวอย่าง\n" +
            "Name[tr]=Örnekler\n" +
            "Name[tt]=Мисаллар\n" +
            "Name[ug]=مىساللار\n" +
            "Name[uk]=Приклади\n" +
            "Name[ur]=مثالیں\n" +
            "Name[uz]=Намуналар\n" +
            "Name[vec]=Esempi\n" +
            "Name[vi]=Mẫu ví dụ\n" +
            "Name[wae]=Bischbil\n" +
            "Name[zh_CN]=示例\n" +
            "Name[zh_HK]=範例\n" +
            "Name[zh_TW]=範例\n" +
            "Comment=Example content for Ubuntu\n" +
            "Comment[aa]=Ubuntuh addattinoh ceelallo\n" +
            "Comment[ace]=Contoh aso ke Ubuntu\n" +
            "Comment[af]=Voorbeeld inhoud vir Ubuntu\n" +
            "Comment[am]=ዝርዝር ምሳሌዎች ለ ኡቡንቱ\n" +
            "Comment[an]=Conteniu d'exemplo ta Ubuntu\n" +
            "Comment[ar]=أمثلة محتوى لأوبونتو\n" +
            "Comment[ast]=Conteníu del exemplu pa Ubuntu\n" +
            "Comment[az]=Ubuntu üçün nümunə material\n" +
            "Comment[be]=Узоры дакументаў для Ubuntu\n" +
            "Comment[bg]=Примерно съдържание за Ubuntu\n" +
            "Comment[bn]=উবুন্টু সংক্রান্ত নমুনা তথ্য\n" +
            "Comment[br]=Skouerenn endalc'had evit Ubuntu\n" +
            "Comment[bs]=Primjer sadrzaja za Ubuntu\n" +
            "Comment[ca]=Continguts d'exemple per a l'Ubuntu\n" +
            "Comment[ca@valencia]=Continguts d'exemple per a l'Ubuntu\n" +
            "Comment[ckb]=نموونەی ناوەڕۆکێک بۆ ئوبوونتو\n" +
            "Comment[cs]=Ukázkový obsah pro Ubuntu\n" +
            "Comment[csb]=Przëmiôrowô zamkłosc dlô Ubuntu\n" +
            "Comment[cy]=Cynnwys enghraifft ar gyfer  Ubuntu\n" +
            "Comment[da]=Eksempel indhold til Ubuntu\n" +
            "Comment[de]=Beispielinhalt für Ubuntu\n" +
            "Comment[dv]=އުބުންޓު އާއި އެކަށޭނަ މިސާލުތައް\n" +
            "Comment[el]=Παραδείγματα περιεχομένου για το Ubuntu\n" +
            "Comment[en_AU]=Example content for Ubuntu\n" +
            "Comment[en_CA]=Example content for Ubuntu\n" +
            "Comment[en_GB]=Example content for Ubuntu\n" +
            "Comment[eo]=Ekzempla enhavo por Ubuntu\n" +
            "Comment[es]=Contenido de ejemplo para Ubuntu\n" +
            "Comment[et]=Ubuntu näidisfailid\n" +
            "Comment[eu]=Adibidezko edukia Ubunturako\n" +
            "Comment[fa]=محتویات نمونه برای اوبونتو\n" +
            "Comment[fi]=Esimerkkisisältöjä Ubuntulle\n" +
            "Comment[fil]=Halimbawang laman para sa Ubuntu\n" +
            "Comment[fo]=Dømis innihald fyri Ubuntu\n" +
            "Comment[fr]=Contenu d'exemple pour Ubuntu\n" +
            "Comment[fur]=Contignûts di esempli par Ubuntu\n" +
            "Comment[fy]=Foarbyld fan ynhâld foar Ubuntu\n" +
            "Comment[ga]=Inneachar samplach do Ubuntu\n" +
            "Comment[gd]=Eisimpleir de shusbaint airson Ubuntu\n" +
            "Comment[gl]=Contido do exemplo para Ubuntu\n" +
            "Comment[gu]=Ubuntu માટે ઉદાહરણ સૂચી\n" +
            "Comment[gv]=Stoo Sanpleyr son Ubuntu\n" +
            "Comment[he]=תוכן לדוגמה עבור אובונטו\n" +
            "Comment[hi]=उबुन्टू हेतु उदाहरण सारांश\n" +
            "Comment[hr]=Primjeri sadržaja za Ubuntu\n" +
            "Comment[ht]=Kontni egzanplè pou Ubuntu\n" +
            "Comment[hu]=Mintatartalom Ubuntuhoz\n" +
            "Comment[hy]=Բովանդակության օրինակները Ubuntu֊ի համար\n" +
            "Comment[id]=Contoh isi bagi Ubuntu\n" +
            "Comment[is]=Sýnishorn fyrir Ubuntu\n" +
            "Comment[it]=Contenuti di esempio per Ubuntu\n" +
            "Comment[ja]=Ubuntuのサンプルコンテンツ\n" +
            "Comment[ka]=უბუნტუს სანიმუშო შიგთავსი\n" +
            "Comment[kk]=Ubuntu құжаттар мысалдары\n" +
            "Comment[kl]=Ubuntu-mut imarisaanut assersuut\n" +
            "Comment[km]=ឧទាហរណ៍សម្រាប់អាប់ប៊ុនធូ\n" +
            "Comment[kn]=ಉಬುಂಟುಗೆ ಉದಾಹರಣೆಗಳು\n" +
            "Comment[ko]=우분투 컨텐츠 예시\n" +
            "Comment[ku]=Ji bo Ubuntu mînaka naverokê\n" +
            "Comment[ky]=Ubuntu-нун мисал документтери\n" +
            "Comment[lb]=Beispillinhalt fir Ubuntu\n" +
            "Comment[lt]=Įvairių dokumentų, paveikslėlių, garsų bei vaizdų pavyzdžiai\n" +
            "Comment[lv]=Parauga saturs Ubuntu videi\n" +
            "Comment[mg]=Ohatra ho an'i Ubuntu\n" +
            "Comment[mhr]=Ubuntu-лан документ-влакын пример-влак\n" +
            "Comment[mi]=Mata tauira o Ubuntu\n" +
            "Comment[mk]=Пример содржина за Убунту\n" +
            "Comment[ml]=ഉബുണ്ടുവിനു വേണ്ടിയുള്ള ഉദാഹരണങ്ങള്\u200D\n" +
            "Comment[mr]=उबंटूसाठी घटकांची उदाहरणे\n" +
            "Comment[ms]=Kandungan contoh untuk Ubuntu\n" +
            "Comment[my]=Ubuntu အတွက် နမူနာ မာတိကာ\n" +
            "Comment[nb]=Eksempelinnhold for Ubuntu\n" +
            "Comment[ne]=उबन्टुका लागि उदाहरण सामग्री\n" +
            "Comment[nl]=Voorbeeldinhoud voor Ubuntu\n" +
            "Comment[nn]=Eksempelinnhald for Ubuntu\n" +
            "Comment[nso]=Mohlala wa dikagare tša Ubuntu\n" +
            "Comment[oc]=Exemples de contengut per Ubuntu\n" +
            "Comment[pa]=ਉਬਤੂੰ ਲਈ ਨਮੂਨਾ ਸਮੱਗਰੀ\n" +
            "Comment[pl]=Przykładowa zawartość dla Ubuntu\n" +
            "Comment[pt]=Conteúdo de exemplo para o Ubuntu\n" +
            "Comment[pt_BR]=Exemplo de conteúdo para Ubuntu\n" +
            "Comment[ro]=Conținut exemplu pentru Ubuntu\n" +
            "Comment[ru]=Примеры документов для Ubuntu\n" +
            "Comment[sc]=Esempiu de cabidu pro Ubuntu\n" +
            "Comment[sco]=Example content fur Ubuntu\n" +
            "Comment[sd]=اوبنٽو لاءِ مثال طور ڏنل مواد\n" +
            "Comment[shn]=တူဝ်ႇယၢင်ႇလမ်းၼႂ်း တႃႇ Ubuntu\n" +
            "Comment[si]=උබුන්ටු සඳහා උදාහරණ අන්තර්ගතයන්\n" +
            "Comment[sk]=Ukážkový obsah pre Ubuntu\n" +
            "Comment[sl]=Ponazoritvena vsebina za Ubuntu\n" +
            "Comment[sml]=Saupama Isina Ubuntu\n" +
            "Comment[sn]=Muyenzaniso wehuiswa kuitira Ubuntu\n" +
            "Comment[sq]=Shembull i përmbajtjes për Ubuntu\n" +
            "Comment[sr]=Садржај примера за Убунту\n" +
            "Comment[sv]=Exempelinnehåll för Ubuntu\n" +
            "Comment[sw]=Bidhaa mfano ya Ubuntu\n" +
            "Comment[szl]=Bajszpilnŏ treść dlŏ Ubuntu\n" +
            "Comment[ta]=உபுண்டுவிற்கான எடுத்துகாட்டு உள்ளடக்கங்கள்\n" +
            "Comment[ta_LK]=உபுண்டுவிற்கான எடுத்துகாட்டு உள்ளடக்கங்கள்\n" +
            "Comment[te]=Ubuntu వాడుక విధాన నమూనాలు\n" +
            "Comment[tg]=Мӯҳтавои намунавӣ барои Ubuntu\n" +
            "Comment[th]=ตัวอย่างข้อมูลสำหรับ Ubuntu\n" +
            "Comment[tr]=Ubuntu için örnek içerik\n" +
            "Comment[tt]=Ubuntu өчен документ мисаллары\n" +
            "Comment[ug]=ئۇبۇنتۇنىڭ مىساللىرى\n" +
            "Comment[uk]=Приклади контенту для Ubuntu\n" +
            "Comment[ur]=یوبنٹو کیلئے مثالی مواد\n" +
            "Comment[uz]=Ubuntu учун намуна таркиби\n" +
            "Comment[vec]=Contenuti de esempio de Ubuntu\n" +
            "Comment[vi]=Mẫu ví dụ cho Ubuntu\n" +
            "Comment[wae]=D'Ubuntu bischbildatijä\n" +
            "Comment[zh_CN]=Ubuntu 示例内容\n" +
            "Comment[zh_HK]=Ubuntu 的範例內容\n" +
            "Comment[zh_TW]=Ubuntu 的範例內容\n" +
            "URL=file:///usr/share/example-content/\n" +
            "Icon=folder\n" +
            "X-Ubuntu-Gettext-Domain=example-content\n" +
            "\n" +
            "\n";

    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testZipFileFunctionality() throws IOException {
        String extractedData = "";
        ZipFile zipFile = null;

        try {
            zipFile = new ZipFile("testResource/test.zip");
        } catch (IOException e) {
            e.printStackTrace();
        }

        Enumeration<? extends ZipEntry> entries = zipFile.entries();

        while(entries.hasMoreElements()){
            ZipEntry entry = entries.nextElement();
            InputStream stream = zipFile.getInputStream(entry);
            extractedData += new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        }

        String savedData = Files.readString(Paths.get("testResource/test.zip.data"));

        if (extractedData.equals(savedData)) {
            System.out.println("Extracted zipfile correctly.");
        } else {
            throw new IOException("Couldn't extract zipfile correctly!");
        }
    }
}
